"""Static mappings extracted from the legacy notebooks."""

from __future__ import annotations

FINAL_GENERAL_CATEGORIES = ("PCR", "TBR", "Specialty")

INVALID_REPORTERS = {
    "Special value",
    ":",
    "European Union - 27 countries",
}

EXCLUDED_PARTNERS = {
    "All countries of the world",
    "Extra-EU27",
    "Intra-EU27",
    "Stores and provisions",
    "Stores and provisions within the framework of intra-Union trade",
    "Stores and provisions within the framework of extra-Union trade",
    "Countries and territories not specified",
    "Countries and territories not specified within the framework of intra-Union trade",
    "Countries and territories not specified within the framework of extra-Union trade",
    "Countries and territories not specified for commercial or military reasons",
    "Countries and territories not specified for commercial or military reasons in the framework of intra-Union trade",
    "Countries and territories not specified for commercial or military reasons in the framework of extra-Union trade",
}

TIRE_PRODUCT_TO_HS = {
    "New pneumatic tyres, of rubber": "4011",
    "New pneumatic tyres, of rubber, of a kind used for motor cars, incl. station wagons and racing cars": "401110",
    "New pneumatic tyres, of rubber, of a kind used for buses and lorries (excl. tyres with lug, corner or similar treads)": "401120",
    "Pneumatic tyres, new, of rubber, of a kind used for buses or lorries, with a load index of <= 121": "40112010",
    "Pneumatic tyres, new, of rubber, of a kind used for buses or lorries, with a load index of > 121": "40112090",
    "New pneumatic tyres, of rubber, of a kind used on agricultural or forestry vehicles and machines": "401170",
    "New pneumatic tyres, of rubber, of a kind used on construction, mining or industrial handling vehicles and machines": "401180",
}

TIRE_PRODUCT_TO_CATEGORY = {
    "New pneumatic tyres, of rubber": "All",
    "New pneumatic tyres, of rubber, of a kind used for motor cars, incl. station wagons and racing cars": "PCR",
    "New pneumatic tyres, of rubber, of a kind used for buses and lorries (excl. tyres with lug, corner or similar treads)": "LT&TBR",
    "Pneumatic tyres, new, of rubber, of a kind used for buses or lorries, with a load index of <= 121": "LT",
    "Pneumatic tyres, new, of rubber, of a kind used for buses or lorries, with a load index of > 121": "TBR",
    "New pneumatic tyres, of rubber, of a kind used on agricultural or forestry vehicles and machines": "ARG & FOR",
    "New pneumatic tyres, of rubber, of a kind used on construction, mining or industrial handling vehicles and machines": "GC & Mining & MH",
}

TIRE_CATEGORY_TO_GENERAL = {
    "PCR": "PCR",
    "LT": "PCR",
    "TBR": "TBR",
    "LT&TBR": "LT&TBR",
    "ARG & FOR": "Specialty",
    "GC & Mining & MH": "Specialty",
    "All": "All",
}

VEHICLE_PRODUCT_TO_HS = {
    "Tractors (other than tractors of heading 8709)": "8701",
    "Motor vehicles for the transport of >= 10 persons, incl. driver": "8702",
    "Motor cars and other motor vehicles principally designed for the transport of <10 persons, incl. station wagons and racing cars (excl. motor vehicles of heading 8702)": "8703",
    "Motor vehicles for the transport of goods, incl. chassis with engine and cab": "8704",
    "Special purpose motor vehicles (other than those principally designed for the transport of persons or goods), e.g. breakdown lorries, crane lorries, fire fighting vehicles, concrete-mixer lorries, road sweeper lorries, spraying lorries, mobile workshops and mobile radiological units": "8705",
    "Chassis fitted with engines, for tractors, motor vehicles for the transport of ten or more persons, motor cars and other motor vehicles principally designed for the transport of persons, motor vehicles for the transport of goods and special purpose motor vehicles of heading 8701 to 8705 (excl. those with engines and cabs)": "8706",
    "Works trucks, self-propelled, not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports for short distance transport of goods; tractors of the type used on railway station platforms; parts of the foregoing vehicles, n.e.s.": "8709",
    "Trailers and semi-trailers; other vehicles, not mechanically propelled (excl. railway and tramway vehicles); parts thereof, n.e.s.": "8716",
    "Trailers and semi-trailers of the caravan type, for housing or camping": "871610",
    "Self-loading or self-unloading trailers and semi-trailers for agricultural purposes": "871620",
    "Tanker trailers and tanker semi-trailers, not designed for running on rails": "871631",
    "Trailers and semi-trailers for the transport of goods, not designed for running on rails (excl. self-loading or self-unloading trailers and semi-trailers for agricultural purposes and tanker trailers and tanker semi-trailers)": "871639",
    "Trailers and semi-trailers, not designed for running on rails (excl. trailers and semi-trailers for the transport of goods and those of the caravan type for housing or camping)": "871640",
    "Vehicles pushed or drawn by hand and other vehicles not mechanically propelled (excl. trailers and semi-trailers)": "871680",
    "Electrical vehicles not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports for short distance transport of goods; tractors of the type used on railway station platforms": "870911",
    "Works trucks, self-propelled, not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports for short distance transport of goods; tractors of the type used on railway station platforms (excl. electrical trucks)": "870919",
    "Parts of self-propelled works trucks, not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports for short distance transport of goods, incl. tractors for railways station platforms, n.e.s.": "870990",
}

VEHICLE_EXCLUDED_HS = {"8709", "8716", "8706"}

VEHICLE_HS_TO_GENERAL = {
    "8701": "Specialty",
    "8702": "TBR",
    "8703": "PCR",
    "8704": "TBR",
    "8705": "Specialty",
    "870911": "Specialty",
    "870919": "Specialty",
    "871610": "Other",
    "871620": "Specialty",
    "871631": "TBR",
    "871639": "TBR",
    "871640": "TBR",
    "871680": "Other",
}

PARTNER_TO_CONTINENT = {
    "Belgium": "Europe", "Czechia": "Europe", "Denmark": "Europe", "Finland": "Europe", "France": "Europe",
    "Germany": "Europe", "Hungary": "Europe", "Italy": "Europe", "Luxembourg": "Europe", "Netherlands": "Europe",
    "Poland": "Europe", "Slovenia": "Europe", "Spain": "Europe", "Sweden": "Europe", "Switzerland": "Europe",
    "United Kingdom": "Europe", "Slovakia": "Europe", "Bosnia and Herzegovina": "Europe", "Romania": "Europe",
    "Norway": "Europe", "Liechtenstein": "Europe", "Croatia": "Europe", "Portugal": "Europe", "Greece": "Europe",
    "Ireland": "Europe", "Estonia": "Europe", "Serbia": "Europe", "Lithuania": "Europe", "Bulgaria": "Europe",
    "North Macedonia": "Europe", "Latvia": "Europe", "Malta": "Europe", "Montenegro": "Europe", "Austria": "Europe",
    "Andorra": "Europe", "San Marino": "Europe", "Gibraltar": "Europe", "Albania": "Europe", "Iceland": "Europe",
    "Cyprus": "Europe", "Belarus": "Europe", "Ukraine": "Europe", "Russian Federation": "Europe",
    "Moldova, Republic of": "Europe", "Kosovo": "Europe", "Faroe Islands": "Europe",
    "Yugoslavia": "Europe", "Serbia and Montenegro": "Europe", "Montenegro.1": "Europe", "Armenia": "Europe",
    "Holy See": "Europe",
    "Indonesia": "Asia", "Japan": "Asia", "Korea, Republic of": "Asia", "Philippines": "Asia", "Türkiye": "Asia",
    "Israel": "Asia", "China": "Asia", "Thailand": "Asia", "India": "Asia", "Taiwan": "Asia", "Singapore": "Asia",
    "Viet Nam": "Asia", "Sri Lanka": "Asia", "Oman": "Asia", "Hong Kong": "Asia", "Saudi Arabia": "Asia",
    "Azerbaijan": "Asia", "Cambodia": "Asia", "Qatar": "Asia", "Iran, Islamic Republic of": "Asia",
    "Jordan": "Asia", "Kuwait": "Asia", "Pakistan": "Asia", "Lebanon": "Asia", "Syrian Arab Republic": "Asia",
    "Mongolia": "Asia", "Georgia": "Asia", "Kazakhstan": "Asia", "Kyrgyzstan": "Asia", "Tajikistan": "Asia",
    "Turkmenistan": "Asia", "Uzbekistan": "Asia", "Afghanistan": "Asia", "Bangladesh": "Asia", "Macao": "Asia",
    "Brunei Darussalam": "Asia", "Malaysia": "Asia", "Myanmar": "Asia", "Lao People’s Democratic Republic": "Asia",
    "Timor-Leste": "Asia", "East Timor": "Asia", "Bhutan": "Asia", "Bahrain": "Asia", "Yemen": "Asia", "Iraq": "Asia",
    "Korea, Democratic People’s Republic of": "Asia", "Occupied Palestinian Territory": "Asia",
    "United Arab Emirates": "Asia", "Nepal": "Asia",
    "Morocco": "Africa", "South Africa": "Africa", "Egypt": "Africa", "Nigeria": "Africa", "Côte d’Ivoire": "Africa",
    "Algeria": "Africa", "Cameroon": "Africa", "Libya": "Africa", "Ghana": "Africa", "Angola": "Africa",
    "Ethiopia": "Africa", "Lesotho": "Africa", "Tunisia": "Africa", "Congo, Democratic Republic of": "Africa",
    "Congo": "Africa", "Zambia": "Africa", "Zimbabwe": "Africa", "Tanzania, United Republic of": "Africa",
    "Central African Republic": "Africa", "Mali": "Africa", "Sudan": "Africa", "Cabo Verde": "Africa",
    "Madagascar": "Africa", "Mauritius": "Africa", "Benin": "Africa", "Senegal": "Africa", "Togo": "Africa",
    "Chad": "Africa", "Kenya": "Africa", "Guinea": "Africa", "Somalia": "Africa", "Djibouti": "Africa",
    "Mauritania": "Africa", "Eritrea": "Africa", "Namibia": "Africa", "Gabon": "Africa", "Uganda": "Africa",
    "Burundi": "Africa", "Rwanda": "Africa", "Botswana": "Africa", "Mozambique": "Africa", "Burkina Faso": "Africa",
    "Equatorial Guinea": "Africa", "Gambia": "Africa", "Sierra Leone": "Africa", "Liberia": "Africa",
    "Sao Tome and Principe": "Africa", "Niger": "Africa", "Mayotte": "Africa", "Seychelles": "Africa",
    "Ceuta": "Africa", "Melilla": "Africa", "Saint Helena, Ascension and Tristan da Cunha": "Africa",
    "Guinea-Bissau": "Africa", "Malawi": "Africa", "South Sudan": "Africa", "British Indian Ocean Territory": "Africa",
    "Eswatini": "Africa", "Comoros": "Africa",
    "Canada": "North America", "United States": "North America", "Mexico": "North America",
    "Greenland": "North America", "Bermuda": "North America", "St Pierre and Miquelon": "North America",
    "Belize": "North America", "Costa Rica": "North America", "El Salvador": "North America",
    "Guatemala": "North America", "Honduras": "North America", "Nicaragua": "North America", "Panama": "North America",
    "Jamaica": "North America", "Cuba": "North America", "Haiti": "North America", "Dominican Republic": "North America",
    "Bahamas": "North America", "Barbados": "North America", "Trinidad and Tobago": "North America",
    "Dominica": "North America", "Antigua and Barbuda": "North America", "St Lucia": "North America",
    "Grenada": "North America", "Virgin Islands, United States": "North America",
    "Virgin Islands, British": "North America", "Cayman Islands": "North America",
    "Turks and Caicos Islands": "North America", "Montserrat": "North America",
    "Saint Barthélemy": "North America", "Sint Maarten": "North America", "Curaçao": "North America",
    "Netherlands Antilles": "North America", "Aruba": "North America", "St Vincent and the Grenadines": "North America",
    "Bonaire, Sint Eustatius and Saba": "North America", "St Kitts and Nevis": "North America",
    "Argentina": "South America", "Brazil": "South America", "Venezuela, Bolivarian Republic of": "South America",
    "Chile": "South America", "Uruguay": "South America", "Paraguay": "South America", "Peru": "South America",
    "Colombia": "South America", "Ecuador": "South America", "Bolivia, Plurinational State of": "South America",
    "Guyana": "South America", "Suriname": "South America", "Falkland Islands": "South America",
    "South Georgia and South Sandwich Islands": "South America",
    "Australia": "Oceania", "New Zealand": "Oceania", "Tuvalu": "Oceania", "Nauru": "Oceania",
    "Papua New Guinea": "Oceania", "New Caledonia": "Oceania", "French Polynesia": "Oceania",
    "Pitcairn": "Oceania", "Cook Islands": "Oceania", "Marshall Islands": "Oceania", "Tonga": "Oceania",
    "American Samoa": "Oceania", "Tokelau": "Oceania", "Northern Mariana Islands": "Oceania",
    "Samoa": "Oceania", "Solomon Islands": "Oceania", "Cocos Islands": "Oceania",
    "Christmas Island": "Oceania", "New Zealand Oceania": "Oceania",
    "United States Minor Outlying Islands": "Oceania", "Wallis and Futuna": "Oceania", "Fiji": "Oceania",
    "Vanuatu": "Oceania", "Kiribati": "Oceania", "Guam": "Oceania",
    "Antarctica": "Antarctica", "French Southern Territories": "Antarctica", "Bouvet Island": "Antarctica",
    "High seas": "Other",
}

PARTNER_TO_SUBREGION = {
    "Denmark": "Northern Europe", "Finland": "Northern Europe", "Sweden": "Northern Europe", "Norway": "Northern Europe",
    "Iceland": "Northern Europe", "Estonia": "Northern Europe", "Latvia": "Northern Europe", "Lithuania": "Northern Europe",
    "United Kingdom": "Northern Europe", "Ireland": "Northern Europe", "Faroe Islands": "Northern Europe",
    "Belgium": "Western Europe", "France": "Western Europe", "Germany": "Western Europe", "Luxembourg": "Western Europe",
    "Netherlands": "Western Europe", "Switzerland": "Western Europe", "Liechtenstein": "Western Europe", "Austria": "Western Europe",
    "Italy": "Southern Europe", "Spain": "Southern Europe", "Portugal": "Southern Europe", "Greece": "Southern Europe",
    "Malta": "Southern Europe", "Croatia": "Southern Europe", "Slovenia": "Southern Europe", "Andorra": "Southern Europe",
    "San Marino": "Southern Europe", "Gibraltar": "Southern Europe", "Albania": "Southern Europe", "Bosnia and Herzegovina": "Southern Europe",
    "North Macedonia": "Southern Europe", "Montenegro": "Southern Europe", "Serbia": "Southern Europe", "Kosovo": "Southern Europe",
    "Yugoslavia": "Southern Europe", "Serbia and Montenegro": "Southern Europe", "Montenegro.1": "Southern Europe",
    "Czechia": "Eastern Europe", "Hungary": "Eastern Europe", "Poland": "Eastern Europe", "Slovakia": "Eastern Europe",
    "Bulgaria": "Eastern Europe", "Romania": "Eastern Europe", "Belarus": "Eastern Europe", "Ukraine": "Eastern Europe",
    "Russian Federation": "Eastern Europe", "Moldova, Republic of": "Eastern Europe",
    "China": "Eastern Asia", "Japan": "Eastern Asia", "Korea, Republic of": "Eastern Asia", "Taiwan": "Eastern Asia",
    "Hong Kong": "Eastern Asia", "Macao": "Eastern Asia", "Mongolia": "Eastern Asia", "Korea, Democratic People’s Republic of": "Eastern Asia",
    "Indonesia": "South-Eastern Asia", "Philippines": "South-Eastern Asia", "Thailand": "South-Eastern Asia", "Singapore": "South-Eastern Asia",
    "Viet Nam": "South-Eastern Asia", "Malaysia": "South-Eastern Asia", "Cambodia": "South-Eastern Asia", "Brunei Darussalam": "South-Eastern Asia",
    "Myanmar": "South-Eastern Asia", "Lao People’s Democratic Republic": "South-Eastern Asia", "Timor-Leste": "South-Eastern Asia", "East Timor": "South-Eastern Asia",
    "India": "Southern Asia", "Pakistan": "Southern Asia", "Sri Lanka": "Southern Asia", "Bangladesh": "Southern Asia",
    "Afghanistan": "Southern Asia", "Bhutan": "Southern Asia", "Nepal": "Southern Asia",
    "Kazakhstan": "Central Asia", "Kyrgyzstan": "Central Asia", "Tajikistan": "Central Asia", "Turkmenistan": "Central Asia", "Uzbekistan": "Central Asia",
    "Türkiye": "Western Asia", "Israel": "Western Asia", "United Arab Emirates": "Western Asia", "Saudi Arabia": "Western Asia",
    "Oman": "Western Asia", "Qatar": "Western Asia", "Kuwait": "Western Asia", "Bahrain": "Western Asia", "Iran, Islamic Republic of": "Western Asia",
    "Jordan": "Western Asia", "Lebanon": "Western Asia", "Syrian Arab Republic": "Western Asia", "Iraq": "Western Asia", "Yemen": "Western Asia",
    "Armenia": "Western Asia", "Azerbaijan": "Western Asia", "Georgia": "Western Asia", "Cyprus": "Western Asia", "Occupied Palestinian Territory": "Western Asia",
    "Morocco": "Northern Africa", "Egypt": "Northern Africa", "Algeria": "Northern Africa", "Tunisia": "Northern Africa",
    "Libya": "Northern Africa", "Sudan": "Northern Africa", "Ceuta": "Northern Africa", "Melilla": "Northern Africa",
    "Nigeria": "Western Africa", "Ghana": "Western Africa", "Côte d’Ivoire": "Western Africa", "Liberia": "Western Africa",
    "Sierra Leone": "Western Africa", "Gambia": "Western Africa", "Mali": "Western Africa", "Senegal": "Western Africa",
    "Guinea": "Western Africa", "Benin": "Western Africa", "Togo": "Western Africa", "Niger": "Western Africa", "Mauritania": "Western Africa",
    "Cabo Verde": "Western Africa", "Burkina Faso": "Western Africa", "Guinea-Bissau": "Western Africa",
    "Ethiopia": "Eastern Africa", "Kenya": "Eastern Africa", "Tanzania, United Republic of": "Eastern Africa", "Uganda": "Eastern Africa",
    "Rwanda": "Eastern Africa", "Burundi": "Eastern Africa", "Mozambique": "Eastern Africa", "Madagascar": "Eastern Africa",
    "Mauritius": "Eastern Africa", "Seychelles": "Eastern Africa", "Somalia": "Eastern Africa", "Djibouti": "Eastern Africa",
    "Eritrea": "Eastern Africa", "Zimbabwe": "Eastern Africa", "Zambia": "Eastern Africa", "Mayotte": "Eastern Africa",
    "Malawi": "Eastern Africa", "Comoros": "Eastern Africa", "South Sudan": "Eastern Africa",
    "Cameroon": "Middle Africa", "Congo, Democratic Republic of": "Middle Africa", "Congo": "Middle Africa", "Angola": "Middle Africa",
    "Central African Republic": "Middle Africa", "Chad": "Middle Africa", "Gabon": "Middle Africa", "Equatorial Guinea": "Middle Africa",
    "Sao Tome and Principe": "Middle Africa",
    "South Africa": "Southern Africa", "Namibia": "Southern Africa", "Botswana": "Southern Africa", "Lesotho": "Southern Africa",
    "Eswatini": "Southern Africa",
    "United States": "Northern America", "Canada": "Northern America", "Greenland": "Northern America", "Bermuda": "Northern America",
    "St Pierre and Miquelon": "Northern America",
    "Jamaica": "Caribbean", "Cuba": "Caribbean", "Haiti": "Caribbean", "Dominican Republic": "Caribbean",
    "Bahamas": "Caribbean", "Barbados": "Caribbean", "Trinidad and Tobago": "Caribbean", "Dominica": "Caribbean",
    "Antigua and Barbuda": "Caribbean", "St Lucia": "Caribbean", "Grenada": "Caribbean", "Virgin Islands, United States": "Caribbean",
    "Virgin Islands, British": "Caribbean", "Cayman Islands": "Caribbean", "Turks and Caicos Islands": "Caribbean",
    "Montserrat": "Caribbean", "Saint Barthélemy": "Caribbean", "Sint Maarten": "Caribbean", "Curaçao": "Caribbean",
    "Netherlands Antilles": "Caribbean", "Aruba": "Caribbean", "Bonaire, Sint Eustatius and Saba": "Caribbean",
    "St Vincent and the Grenadines": "Caribbean", "St Kitts and Nevis": "Caribbean",
    "Mexico": "Central America", "Belize": "Central America", "Costa Rica": "Central America", "El Salvador": "Central America",
    "Guatemala": "Central America", "Honduras": "Central America", "Nicaragua": "Central America", "Panama": "Central America",
    "Argentina": "South America", "Brazil": "South America", "Venezuela, Bolivarian Republic of": "South America",
    "Chile": "South America", "Uruguay": "South America", "Paraguay": "South America", "Peru": "South America",
    "Colombia": "South America", "Ecuador": "South America", "Bolivia, Plurinational State of": "South America",
    "Guyana": "South America", "Suriname": "South America", "Falkland Islands": "South America",
    "South Georgia and South Sandwich Islands": "South America",
    "Australia": "Australia and New Zealand", "New Zealand": "Australia and New Zealand", "New Zealand Oceania": "Australia and New Zealand",
    "Christmas Island": "Australia and New Zealand", "Cocos Islands": "Australia and New Zealand",
    "Papua New Guinea": "Melanesia", "New Caledonia": "Melanesia", "Solomon Islands": "Melanesia",
    "Fiji": "Melanesia", "Vanuatu": "Melanesia",
    "Marshall Islands": "Micronesia", "Northern Mariana Islands": "Micronesia", "Nauru": "Micronesia",
    "United States Minor Outlying Islands": "Micronesia", "Kiribati": "Micronesia", "Guam": "Micronesia",
    "Tuvalu": "Polynesia", "Tonga": "Polynesia", "Samoa": "Polynesia", "Cook Islands": "Polynesia", "French Polynesia": "Polynesia",
    "Pitcairn": "Polynesia", "Tokelau": "Polynesia", "American Samoa": "Polynesia", "Wallis and Futuna": "Polynesia",
    "Saint Helena, Ascension and Tristan da Cunha": "Western Africa",
    "British Indian Ocean Territory": "Eastern Africa",
    "Holy See": "Southern Europe",
    "French Southern Territories": "Antarctica",
    "Bouvet Island": "Antarctica",
    "Antarctica": "Antarctica",
    "High seas": "Other",
}
